### ISSUE TITLE
可以单机部署么？

### ISSUE THREAD

**Issue by zhangbc** [my8100/files#1]
[2019-04-04 10:22:07,042] DEBUG    in scrapydweb.utils.check_app_config: Checking connectivity of SCRAPYD_SERVERS
[2019-04-04 10:22:09,170] ERROR    in __main__: Check app config fail: 

Index Group                Scrapyd IP:Port       Connectivity Auth
None of your SCRAPYD_SERVERS could be connected. 
####################################################################################################
Check and update your settings in D:/working/scrapydweb/scrapydweb/scrapydweb_settings_v8.py
1____ None________________ 127.0.0.1:6801________ False______ None

2____ group_______________ localhost:6801________ False______ ('admin', 'zbc12300')
####################################################################################################

**Comment by my8100** [comment]
What do you mean?

**Comment by zhangbc** [comment]
> What do you mean?

How to solve the problem?

**Comment by my8100** [comment]
None of your SCRAPYD_SERVERS could be connected. 
Check and update your settings in D:/working/scrapydweb/scrapydweb/scrapydweb_settings_v8.py

**Comment by zhangbc** [comment]
SCRAPYD_SERVERS = [
    '127.0.0.1:6801',
    # 'username:password@localhost:6801#group',
    ('admin', 'zbc12300', 'localhost', '6801', 'group'),
]


what‘s wrong？

**Comment by my8100** [comment]
https://github.com/my8100/scrapydweb/blob/master/README_CN.md#computer-上手

**Comment by cced3000** [comment]
How to solve the problem?

**Comment by LorenaMendes** [comment]
I had the same problem. To fix it, I started scrapyd in another terminal tab to open the connection and tried again. Worked fine for me, I hope it helps you.
