### ISSUE TITLE
无法配置成功，SCRAPYD_SERVERS有配置还是不行

### ISSUE THREAD

**Issue by cced3000** [my8100/files#2]
![QQ截图20190802104237](https://user-images.githubusercontent.com/300924/62340485-4c8f2880-b512-11e9-873a-d2da2936a1f5.jpg)

![QQ截图20190802103903](https://user-images.githubusercontent.com/300924/62340548-8829f280-b512-11e9-84f7-e374d5e076ba.jpg)

SCRAPYD确定有启动，但始终提示None of your SCRAPYD_SERVERS could be connected.

**Comment by my8100** [comment]
Update the code below, restart scrapydweb and post the log.

https://github.com/my8100/scrapydweb/blob/79ee83f5d99a7d03debc000012965cb697aaf763/scrapydweb/utils/check_app_config.py#L327-L336

```
    def check_connectivity(server):
        (_group, _ip, _port, _auth) = server
        try:
            url = 'http://%s:%s' % (_ip, _port)
            r = session.get(url, auth=_auth, timeout=30)
            assert r.status_code == 200, "%s got status_code %s" % (url, r.status_code)
        except Exception as err:
            logger.error(err)
            return False
        else:
            return True
```

**Comment by cced3000** [comment]
thanks. The problem has been solved
