### ISSUE TITLE
Cannot set scrapyd auth username and password?

### ISSUE THREAD

**Issue by chanalon** [my8100/files#4]
I set the basic auth on scrapyd, but when I edit scrapydweb settings file with below:
`SCRAPYD_SERVERS = [
    ('admin','adminabc','127.0.0.1','6800','group1')
]
`
but occur exception: ip, port, group = re.search(r'^(.*?)(?:\:(.*?))?(?:@(.*?))?$', s.strip()).groups()
AttributeError: 'tuple' object has no attribute 'strip'

Can you help me with this, thanks!

**Comment by my8100** [comment]
What's the version of your scrapydweb?
Maybe you need to get it upgraded:
```
pip install -U scrapydweb
```

**Comment by chanalon** [comment]
I have alrady update，it’s ok。




On 01/08/2020 22:10, LxL wrote:

What's the version of your scrapydweb?
Maybe you need to get it upgraded:

pip install -U scrapydweb
