### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by baturinivan** [my8100/files#9]
Hello! 
Ubuntu 18.04
Created venv with python3.7
```
pip install scrapydweb
scrapydweb
```
Changed the config - added scrapyd server, set auth, binding default to 0.0.0.0, port 5000
Run srapudweb again - ok, running.
Add firewall rule to allow 5000 port tcp

When I open server_ip:5000 and enter auth info I come to 400 bad request error. 
Details of the error is 'Did not attempt to load JSON data because the request Content-Type was not 'application/json'

How to troubleshoot this?

**Comment by fengxuangit** [comment]
same problem

**Comment by ghost** [comment]
pip uninstall Werkzeug
and
pip install Werkzeug==2.0.3

**Comment by baturinivan** [comment]
Thank you, it is working now.
